/*
 * Copyright (C) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import CameraService from './src/main/ets/model/CameraService'
import Logger from './src/main/ets/model/Logger'

export { CameraView } from './src/main/ets/components/cameraview/cameraView'

export { MediaUtils } from './src/main/ets/model/MediaUtils'

export { tempNum, getDurationString } from './src/main/ets/model/TimeUtils'

export { DateTimeUtil } from './src/main/ets/model/DateTimeUtil'


export { CameraService, Logger }

