// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { MessageEvent } from '../notification/message-event.js';
import { StatusEvent } from '../notification/status-event.js';


export enum EventUnion {
  NONE = 0,
  MessageEvent = 1,
  StatusEvent = 2
}

export function unionToEventUnion(
  type: EventUnion,
  accessor: (obj:MessageEvent|StatusEvent) => MessageEvent|StatusEvent|null
): MessageEvent|StatusEvent|null {
  switch(EventUnion[type]) {
    case 'NONE': return null; 
    case 'MessageEvent': return accessor(new MessageEvent())! as MessageEvent;
    case 'StatusEvent': return accessor(new StatusEvent())! as StatusEvent;
    default: return null;
  }
}

export function unionListToEventUnion(
  type: EventUnion, 
  accessor: (index: number, obj:MessageEvent|StatusEvent) => MessageEvent|StatusEvent|null, 
  index: number
): MessageEvent|StatusEvent|null {
  switch(EventUnion[type]) {
    case 'NONE': return null; 
    case 'MessageEvent': return accessor(index, new MessageEvent())! as MessageEvent;
    case 'StatusEvent': return accessor(index, new StatusEvent())! as StatusEvent;
    default: return null;
  }
}
