// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class StatusEvent {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StatusEvent {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStatusEvent(bb:flatbuffers.ByteBuffer, obj?:StatusEvent):StatusEvent {
  return (obj || new StatusEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStatusEvent(bb:flatbuffers.ByteBuffer, obj?:StatusEvent):StatusEvent {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StatusEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

code():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

static startStatusEvent(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addCode(builder:flatbuffers.Builder, code:number) {
  builder.addFieldInt16(0, code, 0);
}

static endStatusEvent(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createStatusEvent(builder:flatbuffers.Builder, code:number):flatbuffers.Offset {
  StatusEvent.startStatusEvent(builder);
  StatusEvent.addCode(builder, code);
  return StatusEvent.endStatusEvent(builder);
}
}
