// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export { BasicScalars } from './example/basic-scalars.js';
export { GameObject } from './example/game-object.js';
export { Color } from './example/color.js';
export { Shape } from './example/shape.js';